# LOG
LOGGER:
  SYSTEM: "./logger/config/system.yaml"
  DIALOGUE: "./logger/config/dialogue.yaml"


# PORT
PORT: 8080
NGROK: true  # trueにすると，ngrokを使って外部からアクセス可能にする
SERVER_URL: "https://mil-ai.net"  # NGROKを使わない場合は，ここにサーバのURLを指定する

# SERVER MAINTENANCE
PUSH_FLAG: false       # サーバ起動中にこのフラグをtrueにすると，全ユーザに MAINTENANCE_MASSAGE を送信
PUSH_MESSAGE: "サーバメンテナンスのお知らせ\n\n[2025年8月1日 00:00 - 01:00]\n\n上記の時間帯はサーバメンテナンスのため、LINEボットのサービスを一時停止いたします。\n\nご不便をおかけしますが、何卒ご理解のほどよろしくお願いいたします。"
DEBUG_PUSH_MESSAGE: false  # trueのとき，メッセージをデバッグ用のユーザに送信
DEBUG_USER_ID: ""  # デバッグ用のユーザID
RICHMENU_FLAG: false  # trueにすると，全ユーザにメンテナンス用リッチメニューを適用する

# API KEYS
OPENAI_API_KEY: ''
GOOGLE_API_KEY: ''
ANTHROPIC_API_KEY: "XXXXXXXXX無しでも動くXXXXXXXXXXX"
TELEGRAM_KEY: "XXXXXXX無しでも動くXXXXXXXX"


# LINE
LINE_CHANNEL_SECRET: ''
LINE_ACCESS_TOKEN: ''
STAMP: true  # trueにすると，スタンプに対しても応答する


# Stripe
STRIPE_SECRET: ''
STRIPE_WEBHOOK: ''


# Model設定
MODEL_TYPE: "gemini"  # "openai" または "gemini" を指定
OPENAI_MODEL: "gpt-4.1-2025-04-14"
GEMINI_MODEL: "gemini-2.0-flash-lite"
TEMPERATURE: 0.0
MAX_TOKENS: 512


# データベースpath
SESSIONS_DB: "database/sessions.db"
LINEBOT_DB: "database/linebot.db"


# リッチメニューID path
RICHMENU_PATH: "config/richmenu.yaml"


# 同意設定
NEED_START_KEYWORD: true
KEYWORD_MESSAGE: "こちらはカウンセラーAI ミライとのチャットルームです！\n\nカウンセラーAI ミライは電気通信大学稲葉研究室の研究の一環で作成されました．会話の前に，まずは以下のURLにアクセスし研究の趣旨のご理解をお願いします．\n\nhttps://docs.google.com/document/d/1xlpFkZBitE16UmJJ-cKztPR9NsXfImfm3o5oxcfi81M/edit?usp=sharing\n\n本研究の趣旨を十分理解し，協力しても良いと考えられた場合は，「同意する」をタップしてください．"


# 対話開始時のメッセージ
INIT_MESSAGE: "ここでは私、カウンセラーAI ミライ(MIL-AI)があなたの話をお聴きします。話したいことを入力して送信してください。なお、AIは勉強中ですので・・・もしかしたらあなたの予想外のお返事をしてしまうかもしれません。\n\nつらいと感じられた時などは、メニューから、いつでも会話を終わらせることができますので、よろしくお願いします。\n\nまずは、差し支えなければ年齢と性別をお伺いしてもよろしいでしょうか？（答えたくない場合は、答えなくても大丈夫です）"


# 対話言語
LANGUAGE: "Japanese"


# 値段と時間設定
ITEM_1:
  NAME: "1分"
  PRICE: 500
  TIME: 60
ITEM_2:
  NAME: "5分"
  PRICE: 1000
  TIME: 300
ITEM_3:
  NAME: "10分"
  PRICE: 2000
  TIME: 600
ITEM_4:
  NAME: "15分"
  PRICE: 3000
  TIME: 900


# 2択の回答
YES_ANSWER: "はい"
NO_ANSWER: "いいえ"


# アンケート設定
SURVEY:
  SURVEY_INIT_MESSAGE: "ご利用ありがとうございました。AI改善のためのアンケートにご協力いただけますか？（所要時間5分）"
  SURVEY_MESSAGES: [
      "回答は選択肢をタップしてください。\n\nAIと自然なやりとりができた",
      "AIはあなたに対して積極的な関心を抱いていた",
      "AIは自分のことを理解してくれた",
      "AIは信頼できる",
      "AIと話していて安心した気持ちになった",
      "自分の気持ちが整理され，明確になった",
      "相談したいことができたときにAIをまた利用したい",
      "以降はあなたに関するアンケートです。\n\nあなたは活発、外向的だと思う",
      "あなたは他人に不満をもち、もめごとを起こしやすいと思う。",
      "あなたはしっかりしていて、自分に厳しいと思う。",
      "あなたは心配性で、うろたえやすいと思う",
      "あなたは新しいことが好きで、変わった考えをもつと思う",
      "あなたはひかえめで、おとなしいと思う",
      "あなたは人に気をつかう、やさしい人間だと思う",
      "あなたはだらしなく、うっかりしていると思う",
      "あなたは冷静で、気分が安定していると思う",
      "あなたは発想力に欠けた、平凡な人間だと思う",
                    ]
  SURVEY_LAST_MESSAGE: "最後に、なにかご感想があればメッセージ欄に記入して送信してください。特になければ「なし」と送信してください。"
  FINISH_MESSAGE: "ご利用ありがとうございました。"

  VERYGOOD: "とてもそう思う"
  GOOD: "そう思う"
  FAIR: "どちらとも言えない"
  BAD: "そう思わない"
  VERYBAD: "全くそう思わない"
